apiVersion: v1
kind: Pod
metadata:
  name: my-pod-volume
spec:
  containers:
    - name: my-con
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
